### ISSUE TITLE
PIP version incompatible with Python 3.6; Add support for Python 3.9

### ISSUE THREAD

**Issue by me-abudu** [ardnt/vercel-python-wsgi#6]
```
----> Installing pip
--
23:19:30.195 | Running "python3.6 get-pip.py"
23:19:30.246 | ERROR Could not install pip
23:19:30.248 | Error: Command failed: python3.6 /tmp/5784e6cd/get-pip.py --user
23:19:30.249 |  
23:19:30.249 | ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
```
I got this error when i use vercel-python-wsgi today, I tried to use python3.8&3.9 ,but it  told me that python3.8&3.9 both not supported, what can I do

**Comment by K-Zanaty** [comment]
@jayhale I have the same issue from today on.
Would also request some help here.

**Comment by jayhale** [comment]
@me-abudu, @K-Zanaty looks like Vercel deprecated 3.6 and 3.9 is not yet supported by this builder.

The fix is straightforward, need to update these lines and add tests for the new environment:
https://github.com/ardnt/vercel-python-wsgi/blob/8bd112ad2ec28e4d306688b40539d8f571debedf/build-utils/python.js#L7-L8

Feel free to create a PR if you're comfortable - otherwise you might try the [official builder](https://vercel.com/docs/runtimes#official-runtimes/python) in the meantime.

**Comment by am-abudu** [comment]
> @me-abudu, @K-Zanaty looks like Vercel deprecated 3.6 and 3.9 is not yet supported by this builder.
> 
> The fix is straightforward, need to update these lines and add tests for the new environment:
> 
> https://github.com/ardnt/vercel-python-wsgi/blob/8bd112ad2ec28e4d306688b40539d8f571debedf/build-utils/python.js#L7-L8
> 
> Feel free to create a PR if you're comfortable - otherwise you might try the [official builder](https://vercel.com/docs/runtimes#official-runtimes/python) in the meantime.

I dont know how to use django with the official builder, so I want to use this builder. so can I just modify this line to fix this bug?

**Comment by NatanFS** [comment]
I am having the same problem.

**Comment by NatanFS** [comment]
@me-abudu, @K-Zanaty and @am-abudu, I modified the builder so that it can run with python3.9. You can use the package "@natanffs/vercel-python-wsgi" while they don't update this one.

**Comment by jayhale** [comment]
> @me-abudu, @K-Zanaty and @am-abudu, I modified the builder so that it can run with python3.9. You can use the package "@natanffs/vercel-python-wsgi" while they don't update this one.

@NatanFS happy to review a pull request if you create one here.

**Comment by LowScarlet** [comment]
> @me-abudu, @K-Zanaty and @am-abudu, I modified the builder so that it can run with python3.9. You can use the package "@natanffs/vercel-python-wsgi" while they don't update this one.

I got error `Cannot convert undefined or null to object` how to fix?

**Comment by am-abudu** [comment]
> > @me-abudu, @K-Zanaty and @am-abudu, I modified the builder so that it can run with python3.9. You can use the package "@natanffs/vercel-python-wsgi" while they don't update this one.
> 
> I got error `Cannot convert undefined or null to object` how to fix?

Maybe you can use vercel official runtime instead.
See https://github.com/Qexo/Qexo/commit/0ae79ac9e0d764610b2edb38b5ef12dc3c18e17d
